# Generated by Django 3.1.4 on 2020-12-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201203_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Superuser'), (2, 'Teacher'), (3, 'Student')], default=7, null=True),
        ),
    ]
