# Generated by Django 3.1.4 on 2020-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201203_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Superuser'), (2, 'Teacher'), (3, 'Student')], default=3, null=True),
        ),
    ]
